version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pdepend/pdepend
    versions:
    - 2.8.0
    - 2.9.0
  - dependency-name: squizlabs/php_codesniffer
    versions:
    - 3.5.8
