# .travis.yml
language: php
php:
  - 5.6
  - 7.0

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev
before_script:
  - mkdir -p build/logs
script:
  - bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry php vendor/bin/coveralls -v