<?php

/**
 * Created by PhpStorm.
 * User: PBX_g33k
 * Date: 22-May-16
 * Time: 20:05
 */
class Test extends PHPUnit_Framework_TestCase
{
    /**
     * @var \Pbxg33k\MusicInfo\MusicInfo
     */
    private $musicInfo;

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $config = \Symfony\Component\Yaml\Yaml::parse(file_get_contents(__DIR__ . '/../config/config.yml'));
        $this->musicInfo = new \Pbxg33k\MusicInfo\MusicInfo($config['music_info']);
    }

    public function testMusicServiceClient()
    {
        $this->assertInstanceOf('GuzzleHttp\ClientInterface', $this->musicInfo->getClient());
    }
}
