music_info:
    init_services: false
    services:
        - VocaDB
        - Spotify
        # - Discogs
        # - MusicBrainz
    preferred_order:
        # - MusicBrainz
        - Spotify
        - VocaDB
    # Give a weight per service
    # This will be used to *guess* the correct
    # value if multiple services return different values
    service_weight:
        - { VocaDB: 10 }
    guzzle:
        proxy: null
    # General config shared across services
    # Mainly Guzzle
    defaults:
        guzzle:
            http:
                user_agent: 'your-app-name/0.0.1 +https://www.myawsomesite.com'
    # Service Specific config
    vocadb:
        language: Default # default, japanese, romaji, english
        start: 0
        max_entries: 10
        get_total_count: false
        name_match_mode: partials # auto, partial, exact, starts_with, words
    spotify:
        client_id: 7c97efb230be4b6fbacd725695aa2cf6
        client_secret: 61ec7f83a350446abb3c0ad9c5adf371
        redirect_uri: null
        scopes:
          - playlist-read-private
          - user-read-private
    discogs:
        throttle: true
    musicbrainz:
        application_name: Meuk
        application_version: 0.0.1
        application_url: http://www.hoehel.be