<?php
/**
 * Created by PhpStorm.
 * User: PBX_g33k
 * Date: 31-May-16
 * Time: 23:28
 */

namespace Pbxg33k\MusicInfo\Service\MusicBrainz;

use GuzzleHttp\Client;
use MusicBrainz\HttpAdapters\GuzzleFiveAdapter;
use MusicBrainz\MusicBrainz;
use Pbxg33k\MusicInfo\Service\BaseService;
use Pbxg33k\MusicInfo\Service\MusicBrainz\Endpoint\Artist;

class Service extends BaseService
{
    /**
     * @var MusicBrainz
     */
    protected $musicBrainz;

    /**
     * @var Artist
     */
    protected $artist;

    /**
     * {@inheritdoc}
     */
    public function init($config = [])
    {
        if (empty($config)) {
            $config = $this->getConfig();
        }

        $this->musicBrainz = new MusicBrainz(new GuzzleFiveAdapter(new Client()));
        $this->musicBrainz->setUserAgent($config['application_name'], $config['application_version'], $config['application_url']);

        $this->artist = new Artist($this);

        $this->setApiClient($this->musicBrainz);
        $this->setInitialized(true);
    }

    /**
     * @return MusicBrainz
     */
    public function getApiClient()
    {
        return parent::getApiClient(); // TODO: Change the autogenerated stub
    }

    public function artist()
    {
        return $this->artist;
    }
}